### ISSUE TITLE
Preguntas de Investigación Mi Proyecto de Analisis Espacial

### ISSUE THREAD

**Issue by MirelSIG** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-MirelSIG#1]
1. ¿ Cuál es el patrón de distribución de precipitaciones sobre el territorio de la República Dominicana?
2.	¿Las estaciones pluviométricas están apropiadamente distribuidas y con datos fiables suficientes para aplicar metodologías de inferencia estadística de patrones distribución de lluvias en el territorio dominicano? 
3.	¿Las estaciones pluviométricas dispuestas en el territorio de la República Dominicana permiten inferir el patrón de distribución de lluvias mediante el empleo de variogramas y el interpolador krigging?

**OBJETIVOS
GENERAL**
Diseñar el patrón de distribución de precipitaciones sobre el territorio de la República Dominicana a partir de los datos generados en las estaciones pluviométricas del territorio nacional.
**ESPECIFICOS**
1.	Evaluar la idoneidad de datos disponibles en las estaciones pluviométricas de la República Dominicana en cuanto a distribución espacial, calidad y cantidad, para la aplicación de metodologías de inferencia estadística a los patrones de distribución de lluvias en el territorio nacional.
2.	Determinar la existencia de clusters de concentración de precipitaciones y tendencias a la sequía en el territorio dominicano
3.	Construir modelo de predicción del patrón de precipitaciones en el territorio dominicano a partir de los estadígrafos generados por interpolación Krigging.

**Comment by geofis** [comment]
@MirelSIG 

Nunca comenté sobre este texto. Me parece bien planteado, aunque el texto está escrito en forma de temas, no de preguntas, pero me parece bien en todo caso.

Observar estas cuestiones, que surgirán sobre la marcha (sólo tenerlas en cuenta):

* La "idoneidad de datos disponibles" no es tan fácil evaluarla, porque dependerá mucho de a qué denominemos "idóneo". Ahora bien, un análisis de vecindad al menos dice qué distancia promedio existe entre observatorios; si la misma cumple los estándares de la OMM (WMO), pues al menos ya se podría decir algo.

* Para 2 y 3 es mejor elegir un año, aunque puedes elegir varios o todos. Sólo tenerlo en cuenta. Normalmente, usando código, el problema es hacer un año; una vez hecho el primero, los demás no cuestan.

* Para 2 se puede plantear "a nivel municipal" (*hotspots* de precipitación por municipios; *coldspots* de precipitación por municipios).

* Sobre sequía no estoy seguro de que se pueda decir gran cosa sólo a partir de los observatorios, porque para establecer si hay sequía existen métodos que superan esta asignatura.

**Comment by MirelSIG** [comment]
@geofis Evaluando las variables, los coeficientes de correlación entre DENSIDAD DE DRENAJE y las demás, solo Elongation Ratio (-0.545994239) y Shape factor (-0.66948523) cumplen con los términos discutidos en la asesoría del jueves.
Puedo trabajar entonces estableciendo el orden de jerarquía de las microcuencas comparando sus valores de densidad de drenaje?

**Comment by geofis** [comment]
@MirelSIG Perfecto. Podrías usar la variable "densidad de drenaje" para analizar si hay autocorrelación primero y, luego, construir un modelo SAR con `densidad de drenaje ~ elongation ratio + shape factor`.

Recuerda elegir un orden de red, y filtrar las microcuencas para dicho orden de red (de ahí que usara la función `filter` el jueves pasado). De esta manera te aseguras de analizar "entre iguales". Recuerdo que el panel que hicimos el pasado jueves con `ezCor` se refería únicamente a las microcuencas de orden 1. En todo caso, puedes trabajar con cualquier otro orden, pero no mezclando distintos órdenes. Por ejemplo, analizando las microcuencas de orden 1, podría haber correlación de densidad de drenaje con la elongation ratio y el shape factor. Sin embargo, dicha correlación no tendría por qué ser igual para las microcuencas de orden 2. 

No sé si comprendo tu última pregunta, pero me parece que la respondí en el párrafo anterior.

**Comment by MirelSIG** [comment]
@geofis Gracias... si respondida.
Estoy clara en la clasificación del orden: ocoa %>% dplyr::filter(Max_order_Strahler==**1**)
