### ISSUE TITLE
ERROR: Error in moran.plot(x = logDD, listw = ww) :    could not find function "moran.plot"

### ISSUE THREAD

**Issue by MirelSIG** [maestria-geotel-201902/unidad-0-asignacion-99-mi-proyecto-MirelSIG#2]
@geofis , dos dudas, la primera el error al correr el script y la segunda la fuente de los datos:  fuentedatos = 'SRTM'

#LISA Cluster variable dependiente transformada
moran.plot(x = logDD, listw = ww)
lisamap(objesp = Varselpol3,
        var ='logDD',
        pesos = PesoW,
        tituloleyenda = 'Significancia\n("x-y", léase\ncomo "x"\nrodeado de "y"',
        leyenda = T,
        anchuratitulo = 1000,
        tamanotitulo = 16,
        fuentedatos = 'SRTM',
        titulomapa = paste0('Clusters LISA de Log DD'))

**Comment by geofis** [comment]
No vi qué mensaje de error ocurre, sólo el script.

[SRTM](https://www2.jpl.nasa.gov/srtm/) son las siglas del Shuttle Radar Topography Mission. Se consideraría esa la fuente del trabajo, porque de dicho DEM fue de donde se obtuvieron las cuencas mediante procesamiento.

En [este trabajo](http://www.ccsenet.org/journal/index.php/jgg/article/view/0/39703), lo cito así:

>NASA LP DAAC. (2000). SRTM 1 Arc-Second Global. Retrieved from https://earthexplorer.usgs.gov/. NASA EOSDIS Land Processes DAAC, USGS Earth Resources Observation and Science (EROS) Center, Sioux Falls, South Dakota. (published September 2014, accessed May 2016)

La entrada BibTeX que usé fue ésta:

```
@misc{nasa2014srtm1sdem,
  author={{NASA LP DAAC}},
  title={{SRTM 1 Arc-Second Global}},
  year={2000},
  address={NASA EOSDIS Land Processes DAAC, USGS Earth Resources Observation and Science (EROS) Center, Sioux Falls, South Dakota},
  howpublished={\url{https://earthexplorer.usgs.gov/}},
  note={published September 2014, accessed May 2016}
}
```

**Comment by MirelSIG** [comment]
@geofis El error:
Error in moran.plot(x = logDD, listw = ww) : could not find function "moran.plot"

**Comment by geofis** [comment]
Verifica si el paquete `spdep` está cargado más arriba mediante `library(spdep)`

**Comment by MirelSIG** [comment]
Gracias
